### ISSUE TITLE
Profit calculation error

### ISSUE THREAD

**Issue by iamoskvin** [claudioge/arbitrageBots#1]
I suppose that there is a calculation mistake in this code.
In the screenshot you can see the profitable deals.
I modified the code like this to print just profitable:
if outcome > OPPORTUNITY_THRESHOLD:
        print('executeOrder')
        logAndPrint(ex1,ask1,ex2,bid2,fee1,fee2,outcome,tradingPair)

So, you can see that the sell prices are lower than the buy prices. 
I suppose that maybe the error is here:
mixedOut = TRADE_AMOUNT*_ask1/bid2_-TRADE_AMOUNT
Probably it should be: 
TRADE_AMOUNT*_bid2/ask1_-TRADE_AMOUNT
![image](https://user-images.githubusercontent.com/44796732/178107577-8cac733c-0aa5-4d21-9507-2f36f597547a.png)

**Comment by claudioge** [comment]
Thanks!
